'use client';

const JAPAN_FACTS = [
    'In Japan gibt es über 6.800 Inseln, aber nur etwa 430 davon sind bewohnt.',
    'Japan hat mehr als 200 Vulkane, etwa 100 davon sind noch aktiv.',
    'Der Fuji (3.776 m) ist nicht nur der höchste Berg Japans, sondern auch ein aktiver Vulkan — letzte Eruption 1707.',
    'In Tokyo fahren täglich rund 40 Millionen Menschen mit den Zügen — das sind mehr als die Einwohner von vielen Ländern.',
    'Japanische Züge haben eine durchschnittliche Verspätung von weniger als einer Minute pro Jahr.',
    'Es gibt über 5,5 Millionen Getränkeautomaten in Japan — etwa einen pro 23 Einwohner.',
    'In Japan isst man an vielen Orten keine Suppen mit Löffel sondern trinkt sie direkt aus der Schüssel.',
    'Es ist in Japan üblich, auf Rolltreppen links zu stehen und rechts zu gehen — außer in Osaka, dort ist es umgekehrt!',
    'In Japan gibt es spezielle „Schlafcafés" (Manga Kissa), in denen man günstig übernachten kann.',
    'Capsule Hotels wurden 1979 in Osaka erfunden und kosten ab ca. ¥3.000 pro Nacht.',
    'Japan hat die älteste Monarchie der Welt, die auf das Jahr 660 v. Chr. zurückgeht.',
    'Es gibt in Japan mehr Haustiere als Kinder unter 15 Jahren.',
    'Kirschblüte (Sakura) dauert nur etwa 7–10 Tage — die Japaner feiern sie mit Picknicks (Hanami).',
    'In Japan gibt es über 30.000 Onsen (heiße Quellen), beheizt durch vulkanische Aktivität.',
    'Trinkgeld wird in Japan nicht erwartet und kann sogar als Beleidigung aufgefasst werden.',
    'Die japanische Küche wurde 2013 von der UNESCO als immaterielles Kulturerbe anerkannt.',
    'Öffentliche Toiletten in Japan sind oft wahre Technik-Wunder mit beheiztem Sitz, Bidet und Geräuschfunktion.',
    'In Japan gibt es „Katzen-Cafés" (Neko Café), in denen man mit Katzen Kaffee trinken kann.',
    'Das japanische Wort „Komorebi" (木漏れ日) beschreibt das Sonnenlicht, das durch Blätter fällt — ein eigenes Wort dafür!',
    'In Tokyo gibt es einen Stadtteil namens „Akihabara", der als Mekka für Elektronik und Anime gilt.',
    'An Silvester (Ōmisoka) schlagen die Tempelglocken 108 Mal — einmal für jede Sünde im Buddhismus.',
    'Japan hat vier verschiedene Schriftsysteme: Hiragana, Katakana, Kanji und Romaji.',
    'Der älteste Holzbau der Welt steht in Nara: der Hōryū-ji Tempel, erbaut um 607 n. Chr.',
    'In Japan gibt es „Hundert-Yen-Shops" (100均) — das japanische Pendant zum 1-Euro-Laden.',
    'Sumo ist Japans Nationalsport und die Ringer wiegen oft über 150 kg.',
    'Es gibt in Japan Züge, die wie Katzen aussehen — die „Tama Densha" Linie in Wakayama.',
    'Japanische Schüler putzen ihre Klassenzimmer selbst — es gibt keine Putzfachkräfte in Schulen.',
    'In der Mitte des Shibuya Crossings überqueren bei Grün bis zu 3.000 Menschen gleichzeitig die Straße.',
    'Japaner verschenken oft Süßigkeiten als Souvenir (Omiyage) — es gibt regionale Spezialitäten für jede Präfektur.',
    'Das älteste Unternehmen der Welt ist japanisch: Kongō Gumi, gegründet 578 n. Chr., baut Tempel.',
    '„Wabi-Sabi" (侘寂) ist ein japanisches Konzept, das die Schönheit des Unvollkommenen feiert.',
    'In Japan gibt es Straßen ohne Namen — Adressen basieren auf Blocks und Gebäudenummern.',
    'Der Tsukiji Outer Market in Tokyo verkauft täglich frischesten Fisch, Meeresfrüchte und Street Food.',
    'In Japan verbeugt man sich zur Begrüßung: 15° für Bekannte, 30° für Respektspersonen, 45° für Entschuldigungen.',
    'Japan hat die höchste Lebenserwartung der Welt — besonders auf Okinawa leben überdurchschnittlich viele Menschen über 100.',
    'KitKat ist in Japan extrem beliebt — es gibt über 300 regionale Geschmacksrichtungen wie Matcha, Sake oder Erdbeere.',
    'Der Japanische Garten im Friedenspark Hiroshima symbolisiert Frieden und Wiederaufbau nach der Atombombe.',
    'In japanischen Konbinis kann man rund um die Uhr drucken, Pakete verschicken und sogar Konzerttickets kaufen.',
    'Ramen gibt es in vier Haupt-Stilen: Shio (Salz), Shoyu (Soja), Miso und Tonkotsu (Schwein).',
    'Japan hat eine der niedrigsten Kriminalitätsraten der Welt — verlorene Geldbörsen werden häufig zurückgegeben.',
    'Die Goldene Woche (Ende April bis Anfang Mai) ist die geschäftigste Reisezeit in Japan — Züge und Hotels sind ausgebucht.',
    'In japanischen Hotels findet man oft Yukata-Roben zum Anziehen — auch zum Frühstück darf man sie tragen.',
    'Der Tokyo Tower (333 m) wurde 1958 erbaut und wiegt weniger als der Eiffelturm, obwohl er höher ist.',
    'Japanisches Frühstück besteht traditionell aus Reis, Miso-Suppe, eingelegtem Gemüse und gegrilltem Fisch.',
    'In Japan gibt es „Purikura" — Fotoautomaten mit lustigen Filtern und Stickern, besonders beliebt bei Teenagern.',
    'Die japanische Kirschblütenvorhersage (Sakura Zensen) wird so ernst genommen wie der Wetterbericht.',
    'Auf Okinawa gibt es eine einzigartige Kultur mit eigener Musik, Küche und sogar eigenen Kampfkünsten (Karate!).',
    'In Japan kann man an vielen Bahnhöfen „Ekiben" kaufen — regionale Bento-Boxen, speziell für Zugreisende.',
    'Der Fushimi-Inari-Taisha in Kyoto hat über 10.000 rote Torii-Tore auf dem Bergpfad.',
    'Japanische Convenience Stores ändern ihr Sortiment saisonal — Eis im Sommer, Oden im Winter.',
];

export default JAPAN_FACTS;
